# Source configuration that generates Clash and Quantumult X configs.
subscriptions:
- name: V2Club
  type: clash
  url: https://sub.v2club.top/api/v1/client/subscribe?token=90cc293a40e07f4387655fdf6722225f 
proxies:
- name: üáØüáµ„ÄåV2ray„Äçbwh-jp-01
  type: vmess
  server: bwh-jp-01.rundong.me
  port: 443
  uuid: 58f8ac73-d0ea-4e34-bdeb-fdc1f99742fe
  alterId: 0
  cipher: none
  tls: true
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: /whyHkPwvBjUaPBU3vmZaFcy4vgdd3Xrs
    max-early-data: 2048
    early-data-header-name: Sec-WebSocket-Protocol
  udp: true
- name: üáØüáµ„ÄåSS-AES„Äçbwh-jp-01
  type: ss
  server: bwh-jp-01.rundong.me
  port: 17639
  cipher: aes-256-gcm
  password: 67ZByw@MG93HCW@WnbYwfL2ZwbpNHKG3
  udp: true
- name: &ss-chacha-jp-01 üáØüáµ„ÄåSS-ChaCha„Äçbwh-jp-01
  type: ss
  server: bwh-jp-01.rundong.me
  port: 10423
  cipher: chacha20-ietf-poly1305
  password: mkATX*dRrTwX8gVJxdfVyeh3.79xj36P
  udp: true
rules:
- name: Guard
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Unbreak.list
  img-url: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/Hijacking.png
  proxies:
  - DIRECT
- name: AdBlock
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/AdBlock.list
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/AdBlock.png
  proxies:
  - REJECT
  - Mainland
- name: Netflix
  type: select
  filters:
  # Sony TV at bedroom.
  - type: SRC-IP-CIDR
    arg: 192.168.50.27/32
  - type: DOMAIN-SUFFIX
    arg: cookielaw.org
  - type: DOMAIN-SUFFIX
    arg: onetrust.com
  - type: quantumult
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/StreamingMedia/Video/Netflix.list
  - type: clash-ipcidr
    url: https://raw.githubusercontent.com/snapei/clash-pro-rules/release/netflixcidr.txt
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Netflix.png
  proxies:
  - Outside
  - type: regex
    pattern: SG|Singapore|Êñ∞Âä†Âù°|üá∏üá¨
- name: Bilibili & iQIYI
  type: select
  filters:
  - type: clash-classic
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/StreamingSE.yaml
  img-url: https://cdn.jsdelivr.net/gh/Koolson/Qure@master/IconSet/iQIYI%26bilibili.png
  proxies:
  - Mainland
  - type: regex
    pattern: HK|HongKong|È¶ôÊ∏Ø|üá≠üá∞|TW|Taiwan|Âè∞Êπæ|üáπüáº
- name: Microsoft
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Optional/Microsoft.list
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Microsoft.png
  proxies:
  - Mainland
  - Outside
- name: Speedtest
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/GeQ1an/Rules/master/QuantumultX/Filter/Speedtest.list
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Speedtest.png
  proxies:
  - Mainland
  - Outside
- name: Outside
  type: select
  filters:
  - type: DOMAIN-SUFFIX
    arg: s1s1s1.com
  - type: DOMAIN-SUFFIX
    arg: sehuatang.net
  - type: quantumult
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/Global.list
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Outside.png
  proxies:
  - PROXY
- name: Mainland
  type: select
  filters:
  - type: quantumult
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Filter/China.list
  - type: geoip
    arg: CN
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Mainland.png
  proxies:
  - DIRECT
- name: Others
  type: select
  filters:
  - type: match
  img-url: https://cdn.jsdelivr.net/gh/GeQ1an/Rules@master/QuantumultX/IconSet/Others.png
  proxies:
  - PROXY
  - DIRECT
rewrites:
- name: General
  type: quantumult
  url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/General.conf
- name: AdBlock
  type: quantumult
  url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Quantumult/Rewrite/Block/Advertising.conf
generates:
- name: clash
  type: clash
  allow-lan: false
  ipv6: true
  socks-port: 10080
  port: 10081
- name: clash-daemon
  type: clash
  allow-lan: true
  ipv6: true
  socks-port: 10080
  port: 10081
  redir-port: 10082
  tproxy-port: 10083
  external-ui: clash-dashboard
  external-controller: :9090
  dns:
    enable: true
    listen: :10053
    ipv6: true
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    fake-ip-filter:
    - '+.local'
    - '+.rundong.me'
    - localhost.ptlogin2.qq.com
    # Otherwise MS apps and network manager will not operate properly.
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
    # Otherwise IPv6 address acquisition will not operate properly.
    - api6.ipify.org
    nameserver:
    - 192.168.50.1
  profile:
    store-selected: true
    store-fake-ip: true
- name: quantumult-x
  type: quantumult
  general:
    excluded_routes:
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    - 17.0.0.0/8
    geo_location_checker:
    - http://ip-api.com/json/?lang=zh-CN
    - https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/IP_API.js
    server_check_url: http://cp.cloudflare.com/generate_204
    ssid_suspended_list:
    - Rundong's AP
    - Rundong's AP 5GHz
    fallback_udp_policy: *ss-chacha-jp-01
  task_local:
  - name: ÊµÅÂ™í‰Ωì-Ëß£ÈîÅÊü•ËØ¢
    type: event-interaction
    url: https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/streaming-ui-check.js
    img-url: checkmark.seal.system
  - name: GeoIP Êü•ËØ¢
    type: event-interaction
    url: https://cdn.jsdelivr.net/gh/KOP-XIAO/QuantumultX@master/Scripts/geo_location.js
    img-url: location.fill.viewfinder.system
